# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: 김준훈
title: AI Engineer
email: wnsgns05058@naver.com
# email_title: Email (Email title override)
# phone: 01058943787
# phone_title: Phone (Phone title override)
# website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: jekyllrb
github_username:  joonhoonkim
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: jekyll
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# orcid_username: 0000-0000-0000-0000
# googlescholar_username: D847cGsAAAAJ

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile_img.PNG
about_content: | # this will include new lines to allow paragraphs
  3년간 AI 환경에서 일해왔으며 python, pyTorch, opencv를 활용하여 Vision AI 프로젝트를 주로 수행해왔습니다. **clasification과
  object detection, segmentation** 등 다양한 프로젝트를 수행한 경험이 있습니다.
  
  첫 회사가 SI 업체이다 보니 자연스럽게 `고객이 필요로 하는` 프로젝트가 중요하다고 느꼈습니다. 고객 입장에서 필요한 기능과
  알고리즘을 고민하는 개발자입니다.
  
  데이터 수집부터 보고서 작성까지 프로젝트의 A to Z를 수행하였습니다.
  
  현재는 Gen AI 업무를 수행하면서 다양한 AI 관련 프로젝트를 수행하고 있습니다.

content:
  - title: 경력 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: 무브멘토 (movemento)
        sub_title: AI Engineer
        caption: 2023.09 ~ Present
        link: http://movemento.co.kr
        quote: >
          가상 모델 swapping 서비스 및 커머스 프로젝트 PM
        description: | # this will include new lines to allow paragraphs
          - comfyUI와 MIdjourny를 활용하서 가상 모델 생성
          - 촬영한 모델을 가상 모델로 swapping(촬영당 모델비 절감 효과)
          
          - 커머스 프로젝트 QA 및 PM 담당

      - layout: left
        border: weak
        title: 넥스리얼 (nexreal)
        sub_title: AI Engineer
        caption: 2021.01 ~ 2023.08
        link: www.nexreal.com
        quote: >
          SI 개발 담당
        description: | # this will include new lines to allow paragraphs
          - 화재 감지 프로젝트
          - 이상행동 탐지 프로젝트(최종 평가 1등 달성 -> 인천공항 시범 납품)
          - 미상 물체 탐지 프로젝트

  - title: 역량
    layout: list
    content:
      - layout: top-left
        title: 프로젝트 매니징
        sub_title: 행정 업무 및 WBS 관리
        description: | # this will include new lines to allow paragraphs
          - [2023.09 ~ Present, 무브멘토] commerce 프로젝트 관리 및 QA 업무
          - [2023.09 ~ 2024.02, 무브멘토] 창업도약패키지 프로젝트 관리

      - layout: top-left
        title: 서비스 개발
        sub_title: 신규 서비스 분석 및 개발
        description: | # this will include new lines to allow paragraphs
          - [2023.10 ~ Present, 무브멘토] 가상 모델 얼굴 swapping 서비스 개발
          - [2023.01 ~ 2023.02, 넥스리얼] SAM 모델을 활용한 라벨링 서비스 개발
          - [2022.09 ~ 2022.11, 넥스리얼] 사람의 이상행동 중 경로 이탈 탐지 서비스 개발
          - [2022.08 ~ 2022.09, 넥스리얼] 차량 번호판 식별 서비스 개발
          - [2022.05 ~ 2022.08, 넥스리얼] 사람의 이상행동 중 달리기 탐지 서비스 개발
          - [2022.02 ~ 2022.05, 넥스리얼] 사람의 이상행동 중 싸움 탐지 서비스 개발
          - [2022.01 ~ 2022.02, 넥스리얼] 사람 detection 및 key-point detection 개발
          - [2021.05 ~ 2021.10, 넥스리얼] 불꽃 object detection 서비스 개발 
          - [2021.03 ~ 2021.06, 넥스리얼] 불꽃 grid classficiation 서비스 개발

  - title: 기술 스택
    layout: list
    content:
      - layout: left
        title: Vision AI
        description: | # this will include new lines to allow paragraphs
          - python, Java, C++
          - pyTorch, TensorFlow
          - openCV
          - numpy, pandas
          - vscode, IntelliJ, pycharm

      - layout: left
        title: Gen AI
        description: |
          - stable diffusion, comfyUI, Midjourney
          - photoshop

      - layout: left
        title: tools
        description: |
          - putty, tera term
          - vi editor

      - layout: left
        title: collaboration
        description: |
          - slack, trello
          - notion
          

  - title: 학력
    layout: list
    content:
      - layout: top-left
        title: 계명대학교
        sub_title: 컴퓨터공학 학사
        caption: 2014.03 ~ 2021.08
        link: www.kmu.ac.kr
        description: |
          - 컴퓨터공학 학사 졸업

      - layout: top-left
        title: 경신고등학교
        sub_title: 고등학교
        caption: 2010.03 ~ 2013.02
        description: |
          - 이과 계열 졸업

  - title: 활동
    layout: left
    content:
      - layout: top-left
        title: 프로그래머스 인공지능 데브코스 5기 (중도 포기)
        sub_title: 인공지능
        caption: 2023.03 ~ 2023.07
        description: |
          - 프로그래머스에서 진행한 인공지능 데브코스에 선발되어서 활동
          - 지난 기수들과는 다르게 취업자반이 따로 운영되지 않아서 중도 포기 결정함

      - layout: top-left
        title: 공공빅데이터 청년인턴십 2기
        sub_title: 빅데이터
        caption: 2020.08 ~ 2020.12
        description: |
          - 빅데이터 관련 교육
          - 시청 소속으로 근무하여 빅데이터 프로젝트 진행

      - layout: top-left
        title: 멋쟁이 사자처럼 7기
        sub_title: 웹
        caption: 2019.01 ~ 2019.12
        description: |
          - 학교 내 동아리로 웹 프로그래밍 활동
          - 웹 관련 교육과 프로젝트 진행
          - 해커톤 진행

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
